---
- hosts: all
  vars:
      - packages:
          RedHat: [vim-enhanced, tmux, ack, git]
          Debian: [vim, ack-grep, tmux, git]
  tasks:
      - name: Install EPEL
        yum: name=epel-release state=installed
        when: ansible_os_family == "RedHat"

      - name: Install a few nice-to-have packages
        package: name={{ item }} state=present
        with_items: "{{ packages[ansible_os_family] }}"

      - name: Remove EPEL
        yum: name=epel-release state=absent
        when: ansible_os_family == "RedHat"
